#import Caloriesneeded as cn
#Create the suggested dish when male/female is deficient in daily calorie intake:
food = {
        100: 'Go to a grocery store and buy an apple.',
        200: 'oatmeal: 1 cup rolled oats, 2 cups unsweetened almond milk, 1 medium banana, 1/2 teaspoon vanilla extract, 1/2 teaspoon cinnamon, and a pinch of salt.',
        300: 'three fried eggs: 1/2 teaspoon olive oil, 3 eggs, and a pinch of salt and pepper.',
        400: 'Go to a grocery store and buy a bag of Orville Redenbacher popcorn, no butter added.',
        500: 'grilled chicken salad: 1 grilled chicken breast, 1 cup of chopped lettuce, 1 tomato, 1 cucumber, 1 avocado, 2 tablespoons of lemon juice, 1 tablespoon olive oil, 1/4 teaspoon salt and pepper, and 2 garlic cloves.',
        600: 'Jamaican chicken with rice and peas: For the chicken, gather 4 chicken legs (skin removed), 1 tablespoon rapeseed oil, 2 sliced red onions, 1 tablespoon thyme leaves, 4 chopped tomatoes, 2 carrots and 5 broccoli stems steamed, 1 tablespoon curry powder, and 2 garlic cloves.  For the rice and peas, gather 125 grams brown rice, 1 chopped red onion, 2 garlic cloves, 1 tablespoon thyme leaves, 2 tablespoon peas, and 400 grams black beans can.',
        700: 'Burger King Chicken Sandwich: One white meat, seasoned and breaded, chicken filet, 1 piece of lettuce, 1 slice tomato, 1 tablespoon mayonnaise all on a potato bun.',
        800: 'Four Stack Cupcake Pancakes: For the pancakes, gather 1-1/2 cups flour, 1-1/2 teaspoon baking powder, 1/4 teaspoon salt, 2 eggs, 2/3 cup sugar, 3/4 cup unsalted butter, 2 teaspoons vanilla extract, 1 cup whole milk, 2 tablespoons sprinkles, and 2 tablespoons butter for greasing the skillet. For the frosting, gather 1/2 cup whipping cream, 1 teaspoon vanilla extract, and 1 cup powdered sugar.',
        900: 'Chicken Florentine Crepes: For the Chicken Florentine, gather 1 lb chicken breast, 3 garlic cloves, 1 10 ounce can cream of chicken soup, 4 ounces cheddar cheese, 10 ounces spinach, 1/2 cup whole milk, 2 tablespoons butter, and 2 tablespoons salt and pepper.  For the Crepe, gather 1 cup flour, 1 cup milk, 4 eggs, 1 tablespoon butter, and 1/2 teaspoon salt',
        1000: 'Chicken and Waffles: For the chicken, gather 4 chicken strips, 1 cup buttermilk, 1-1/2 cups flour, 1/2 tablespoon salt, 1/2 teaspoon paprika, 1/2 teaspoon black pepper, 1/2 teaspoon ground thyme, 1/4 teaspoon cayenne, 1/8 cup milk, and vegetable oil for frying.  For waffles, gather 2 cups flour, 1/4 cup sugar, 1 tablespoon baking powder, 1/2 teaspoon salt, 1-1/2 cups milk, 1 tablespoon vanilla extract, 4 egg whites and 2 egg yolks, 8 tablespoons salted butter, and 1-2 chopped jalapenos.  For the sauce, gather 1 cup maple syrup, 1/4 cup bourbon, 4 tablespoon salted butter, and 1/4 teaspoon cayenne.',
        1100: 'Classic Skillet Cornbread: 2-1/2 cups coarse-grind cornmeal, 1-1/4 baking soda, 1-1/4 teaspoon salt, 1 egg, 1-2/3 cups buttermilk, and 2 unsalted butter.',
        1200: 'Buttermilk Biscuits slathered in Country Gravy: For the biscuits, gather 3 biscuits, 2 cups flour, 2 teaspoons baking powder, 1 teaspoon salt, 1/2 teaspoon baking soda, 8 tablespoons unsalted butter, and 1 cup buttermilk. For the gravy, gather, 3 tablespoon unsalted butter, 12 ounces sausage, 1/3 cup flour, 1/2 teaspoon salt, 1/2 teaspoon black pepper, 1/8 teaspoon cayenne pepper, and 3-1/2 cups whole milk.',
        1300: 'Machacha: 2 flour tortillas, 2-3 pounds chopped steak, 3 tablespoon vegetable oil, 1 large chopped white onion, 1 red bell pepper, 1 green bell pepper, 2 serrano chiles, 1 cup beef broth, 1 can diced tomatoes, 1/2 teaspoon oregano, and a pinch of salt and pepper.',
        1400: 'Cheeseburger Omelette: 1 tablespoon olive oil, 1/4 pound ground beef, 3 eggs, 1 tablespoon butter, 2 slices American cheese, pinch of salt and pepper, 1 tablespoon ketchup, 1 tablespoon mayonnaise, 1 teaspoon mustard, 1/4 teaspoon hot sauce, 1 tablespoon relish, and 1 tablespoon scallions',
        1500: 'Meat Pie: 1 potato, 1/2 lb ground beef, 1/2 lb ground pork, 1/3 garlic cloves, 1/2 cup onion, 1/4 cup water, 1/2 teaspoon mustard powder, 1/2 teaspoon thyme, 1/2 teaspoon cloves, 1 teaspoon salt, 1/4 teaspoon black pepper, 1/4 teaspoon sage, and 1 (15 oz) pie crust.',
        1600: '13 Buttermilk Crispy Tenders: 13 chicken tenders, 1 cup buttermilk, 1-1/2 teaspoon salt, 1/4 teaspoon cayenne, 1/4 teaspoon garlic powder, 1/4 teaspoon paprika, 1-1/2 cup flour, 1 teaspoon salt, 3/4 teaspoon black pepper, 3/4 teaspoon garlic powder, 1-1/2 teaspoon baking powder, 3-4 cups vegetable oil',
        1700: '38 Chicken Nuggets: 13 chicken breasts to cut into 38 small pieces, 1 cup flour, 1 tablespoon salt and pepper, 2 eggs, 2 cups seasoned breadcrumbs, vegetable oil for frying',
        1800: '2 Fully-Loaded Egg Burritos: 6 eggs, 3 tablespoons reduced fat milk, 1/4 teaspoon salt, 1/8 teaspoon pepper, 1 pound sausage, 1/2 cup onion, 1 can (10 oz) diced tomatoes, 2 flour tortillas, and 1 cup cheddar cheese',
        1900: '3 Double Quarter Pounders, no ketchup or cheese: 1 pound ground chunk, 1/2 pound lean, ground beef, 4 tablespoons salt, 1-1/2 teaspoon pepper, 1/2 tablespoon onion powder, 1/4 teaspoon garlic powder, 4 tablespoons chopped onion, and 3 sesame seed buns',
        2000: '2 Bacon Swiss Sourdough King: 2 meat patties, 1 slice American cheese, 2 thick cut bacon pieces, 1/4 pound sliced onions, 2 squirts of mustard mayonnaise sauce, and a sourdough bun'}

#c=cn.caloriecalc(6,0,210,28,"female")
#print(c)
